name: currency_calculator
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  tuple: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.2.0

  url_launcher: ^5.0.2
  math_expressions: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/ada.jpg
   - assets/images/atom.jpg
   - assets/images/aud.jpg
   - assets/images/bat.jpg
   - assets/images/bch.jpg
   - assets/images/bchsv.jpg
   - assets/images/bgn.jpg
   - assets/images/bnb.jpg
   - assets/images/brl.jpg
   - assets/images/btc.jpg
   - assets/images/cad.jpg
   - assets/images/chf.jpg
   - assets/images/cny.jpg
   - assets/images/cro.jpg
   - assets/images/czk.jpg
   - assets/images/dash.jpg
   - assets/images/dcr.jpg
   - assets/images/dkk.jpg
   - assets/images/doge.jpg
   - assets/images/eos.jpg
   - assets/images/etc.jpg
   - assets/images/eth.jpg
   - assets/images/eur.jpg
   - assets/images/gbp.jpg
   - assets/images/grph.jpg
   - assets/images/hkd.jpg
   - assets/images/hrk.jpg
   - assets/images/ht.jpg
   - assets/images/huf.jpg
   - assets/images/idr.jpg
   - assets/images/ils.jpg
   - assets/images/inr.jpg
   - assets/images/iot.jpg
   - assets/images/isk.jpg
   - assets/images/jpy.jpg
   - assets/images/krw.jpg
   - assets/images/leo.jpg
   - assets/images/link.jpg
   - assets/images/lsk.jpg
   - assets/images/ltc.jpg
   - assets/images/mkr.jpg
   - assets/images/mxn.jpg
   - assets/images/myr.jpg
   - assets/images/neo.jpg
   - assets/images/okb.jpg
   - assets/images/pax.jpg
   - assets/images/pln.jpg
   - assets/images/qtum.jpg
   - assets/images/ron.jpg
   - assets/images/rub.jpg
   - assets/images/rvn.jpg
   - assets/images/sek.jpg
   - assets/images/sgd.jpg
   - assets/images/thb.jpg
   - assets/images/trx.jpg
   - assets/images/try.jpg
   - assets/images/tusd.jpg
   - assets/images/usd.jpg
   - assets/images/usdc.jpg
   - assets/images/usdt.jpg
   - assets/images/vet.jpg
   - assets/images/xem.jpg
   - assets/images/xlm.jpg
   - assets/images/xmr.jpg
   - assets/images/xrp.jpg
   - assets/images/xtz.jpg
   - assets/images/zar.jpg
   - assets/images/zec.jpg
   - assets/images/zrx.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
